#!/usr/bin/env bash
# Displays listening ports. Includes listening sockets too
# as the PID and name of the program to which each socket belongs.

netstat -l --program

5-is_the_host_on_the_network

#!/usr/bin/env bash
# Pings an IP address received as a string argument 5 times.

if [ "$#" -eq 0 ]
then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
  ping -c 5 "$1"
fi
